name: MediaWiki fetch

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install node-fetch@2 @actions/core @actions/github
          npm install -D @types/node @types/node-fetch typescript
      
      - name: Build script
        run: npx tsc --project tsconfig.actions.json

      - name: Login wiki
        id: login
        env:
          MW_USERNAME: ${{ secrets.MW_USERNAME }}
          MW_PASSWORD: ${{ secrets.MW_PASSWORD }}
          MW_API: ${{ secrets.MW_API }}
        run: node .github/dist/login.js
      
      - name: Upload content
        env:
          MW_API: ${{ secrets.MW_API }}
          MW_CSRF_TOKEN: ${{ steps.login.outputs.token }}
          MW_COOKIE: ${{ steps.login.outputs.cookie }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MW_TARGET_PAGE: "MediaWiki:Gadget-sidebarRecentChanges.js"
          GITHUB_TARGET_DIR: "src/sidebarRecentChanges.js"
        run: node .github/dist/post.js
